-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 14:50:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Curso` (
  `CodCurso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Asignatura` (
  `CodAsignatura` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `CodCurso` INT NOT NULL,
  PRIMARY KEY (`CodAsignatura`),
  INDEX `fk_Asignatura_Curso_idx` (`CodCurso` ASC),
  CONSTRAINT `fk_Asignatura_Curso`
    FOREIGN KEY (`CodCurso`)
    REFERENCES `academia`.`Curso` (`CodCurso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Estudiante` (
  `CodEstudiante` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(400) NULL,
  `CodCurso` INT NOT NULL,
  PRIMARY KEY (`CodEstudiante`),
  INDEX `fk_Estudiante_Curso1_idx` (`CodCurso` ASC),
  CONSTRAINT `fk_Estudiante_Curso1`
    FOREIGN KEY (`CodCurso`)
    REFERENCES `academia`.`Curso` (`CodCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Notas` (
  `CodEstudiante` INT NOT NULL,
  `CodAsignatura` INT NOT NULL,
  `Notas01` INT NULL,
  `Notas02` INT NULL,
  `Notas03` INT NULL,
  `Notas04` INT NULL,
  `Notas05` INT NULL,
  PRIMARY KEY (`CodEstudiante`, `CodAsignatura`),
  INDEX `fk_Estudiante_has_Asignatura_Asignatura1_idx` (`CodAsignatura` ASC),
  INDEX `fk_Estudiante_has_Asignatura_Estudiante1_idx` (`CodEstudiante` ASC),
  CONSTRAINT `fk_Estudiante_has_Asignatura_Estudiante1`
    FOREIGN KEY (`CodEstudiante`)
    REFERENCES `academia`.`Estudiante` (`CodEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Asignatura_Asignatura1`
    FOREIGN KEY (`CodAsignatura`)
    REFERENCES `academia`.`Asignatura` (`CodAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
