-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 21:12:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema registro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registro` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `registro` ;

-- -----------------------------------------------------
-- Table `registro`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NULL DEFAULT NULL,
  `condicion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`articulo` (
  `idarticulo` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `codigo` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idarticulo`),
  INDEX `idcategoria` (`idcategoria` ASC),
  CONSTRAINT `articulo_ibfk_1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `registro`.`categoria` (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `tipo_persona` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `tipo_documento` VARCHAR(20) NULL DEFAULT NULL,
  `num_documento` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(70) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idproveedor` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL DEFAULT NULL,
  `num_comprobante` VARCHAR(10) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `idproveedor` (`idproveedor` ASC),
  CONSTRAINT `ingreso_ibfk_1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `registro`.`persona` (`idpersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`detalle_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`detalle_ingreso` (
  `iddetalle_ingreso` INT NOT NULL AUTO_INCREMENT,
  `idingreso` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_compra` DECIMAL(11,2) NOT NULL,
  `precio_venta` DECIMAL(11,2) NULL DEFAULT NULL,
  PRIMARY KEY (`iddetalle_ingreso`),
  INDEX `idingreso` (`idingreso` ASC),
  INDEX `idarticulo` (`idarticulo` ASC),
  CONSTRAINT `detalle_ingreso_ibfk_1`
    FOREIGN KEY (`idingreso`)
    REFERENCES `registro`.`ingreso` (`idingreso`),
  CONSTRAINT `detalle_ingreso_ibfk_2`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `registro`.`articulo` (`idarticulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `serie_comprobante` VARCHAR(7) NULL DEFAULT NULL,
  `num_comprobante` VARCHAR(10) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `impuesto` DECIMAL(4,2) NULL DEFAULT NULL,
  `total_venta` DECIMAL(11,2) NOT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `idcliente` (`idcliente` ASC),
  INDEX `idusuario` (`idusuario` ASC),
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `registro`.`persona` (`idpersona`),
  CONSTRAINT `venta_ibfk_2`
    FOREIGN KEY (`idusuario`)
    REFERENCES `registro`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registro`.`detalle_venta` (
  `iddetalle_venta` INT NOT NULL AUTO_INCREMENT,
  `idventa` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(11,2) NOT NULL,
  `descuento` DECIMAL(11,2) NULL DEFAULT NULL,
  PRIMARY KEY (`iddetalle_venta`),
  INDEX `idventa` (`idventa` ASC),
  INDEX `idarticulo` (`idarticulo` ASC),
  CONSTRAINT `detalle_venta_ibfk_1`
    FOREIGN KEY (`idventa`)
    REFERENCES `registro`.`venta` (`idventa`),
  CONSTRAINT `detalle_venta_ibfk_2`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `registro`.`articulo` (`idarticulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
